[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ProjectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$SchemaPath = Join-Path $ProjectRoot 'shared\schemas\nutrition-progress.schema.json'
$FixturePath = Join-Path $ProjectRoot 'shared\tests\fixtures\nutrition-progress-cases.json'
$ExpectedSchemaId = 'https://diet-manager.local/schemas/nutrition-progress/v1'
$ExpectedFixtureSetId = 'diet-manager/nutrition-progress-cases/v1'
$ExpectedVersion = '1.0.0'
$ExpectedCaseIds = @(
    'NUTR-PROFILE-COMPLETE-VALID',
    'NUTR-PROFILE-PARTIAL-VALID',
    'NUTR-PROFILE-V2-SUPERSEDES-VALID',
    'NUTR-PROFILE-JSON-NUMBER-INVALID',
    'NUTR-PROFILE-UNKNOWN-ZERO-INVALID',
    'NUTR-PROFILE-ESTIMATED-COVERAGE-INVALID',
    'NUTR-PROFILE-GENERIC-STATUS-INVALID',
    'NUTR-PROFILE-EXTRA-PROPERTY-INVALID',
    'NUTR-SNAPSHOT-COMPLETE-VALID',
    'NUTR-SNAPSHOT-PARTIAL-VALID',
    'NUTR-SNAPSHOT-UNKNOWN-VALID',
    'NUTR-SNAPSHOT-KNOWN-MISSING-OVERLAP-INVALID',
    'NUTR-SNAPSHOT-KNOWN-NULL-INVALID',
    'NUTR-SNAPSHOT-MISSING-NONNULL-INVALID',
    'NUTR-SNAPSHOT-COMPLETE-MISSING-INVALID',
    'NUTR-SNAPSHOT-PROFILE-VERSION-INVALID',
    'NUTR-SNAPSHOT-JSON-NUMBER-INVALID',
    'NUTR-SNAPSHOT-GENERIC-STATUS-INVALID',
    'NUTR-GOAL-SIX-METRICS-VALID',
    'NUTR-GOAL-PARTIAL-CONFIG-VALID',
    'NUTR-GOAL-NO-CONFIRMATION-INVALID',
    'NUTR-GOAL-ALL-UNCONFIGURED-INVALID',
    'NUTR-GOAL-NEGATIVE-INVALID',
    'NUTR-GOAL-EFFECTIVE-RANGE-INVALID',
    'NUTR-GOAL-JSON-NUMBER-INVALID',
    'NUTR-GOAL-EXTRA-METRIC-INVALID',
    'NUTR-PROGRESS-SINGLE-DAY-VALID',
    'NUTR-PROGRESS-CROSS-DAY-CORRECTION-VALID',
    'NUTR-PROGRESS-DIRECT-QUERY-VALID',
    'NUTR-PROGRESS-UNKNOWN-FIBER-VALID',
    'NUTR-PROGRESS-WATER-LOWER-BOUND-VALID',
    'NUTR-PROGRESS-WRONG-ORDER-INVALID',
    'NUTR-PROGRESS-NEGATIVE-TOTAL-INVALID',
    'NUTR-PROGRESS-UNKNOWN-ZERO-INVALID',
    'NUTR-PROGRESS-DIRECT-INCREMENT-INVALID',
    'NUTR-PROGRESS-SINGLE-ALIAS-MISSING-INVALID',
    'NUTR-PROGRESS-SINGLE-ALIAS-MISMATCH-INVALID',
    'NUTR-PROGRESS-MULTI-ALIAS-INVALID',
    'NUTR-PROGRESS-DATE-ORDER-INVALID',
    'NUTR-PROGRESS-DUPLICATE-DATE-INVALID',
    'NUTR-PROGRESS-JSON-NUMBER-INVALID',
    'NUTR-PROGRESS-GENERIC-STATUS-INVALID'
)

function Fail([string]$Code, [string]$Detail) {
    throw "$Code`:$Detail"
}

if (-not [IO.File]::Exists($SchemaPath)) {
    Fail 'NUTRITION_PROGRESS_SCHEMA_FILE_MISSING' $SchemaPath
}
if (-not [IO.File]::Exists($FixturePath)) {
    Fail 'NUTRITION_PROGRESS_FIXTURE_FILE_MISSING' $FixturePath
}

Fail 'NUTRITION_PROGRESS_SCHEMA_SHAPE_INVALID' ('validator implementation must evaluate {0} cases for {1} {2}' -f $ExpectedCaseIds.Count, $ExpectedSchemaId, $ExpectedFixtureSetId)
