[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ProjectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$SchemaPath = Join-Path $ProjectRoot 'shared\schemas\issue-correction-mixed.schema.json'
$FixturePath = Join-Path $ProjectRoot 'shared\tests\fixtures\issue-correction-mixed-cases.json'
$ExpectedSchemaId = 'https://diet-manager.local/schemas/issue-correction-mixed/v1'
$ExpectedFixtureSetId = 'diet-manager/issue-correction-mixed-cases/v1'
$ExpectedVersion = '1.0.0'
$ExpectedDefinitionNames = @(
    'Issue',
    'IssueResolutionEvent',
    'QuickPrompt',
    'CorrectionSnapshot',
    'CorrectionEvent',
    'EffectOutboxEntry',
    'FactCommitResult',
    'EffectBundleResult',
    'ReceiptData',
    'EnvelopeFinalizeResult',
    'MixedItemResult',
    'MixedCommitResult'
)
$ExpectedCaseIds = @(
    'ICM-ISSUE-OPEN-VALID',
    'ICM-ISSUE-AWAITING-USER-VALID',
    'ICM-ISSUE-RESOLVED-VALID',
    'ICM-ISSUE-DISMISSED-VALID',
    'ICM-ISSUE-LEGACY-STATUS-INVALID',
    'ICM-ISSUE-OPEN-CLOSURE-FIELDS-INVALID',
    'ICM-ISSUE-RESOLVED-MISSING-EVENT-INVALID',
    'ICM-ISSUE-CODE-INVALID',
    'ICM-RESOLUTION-APPLIED-VALID',
    'ICM-RESOLUTION-NO-CHANGE-VALID',
    'ICM-RESOLUTION-REJECTED-VALID',
    'ICM-RESOLUTION-REJECTED-MISSING-REASON-INVALID',
    'ICM-RESOLUTION-TECHNICAL-FAILED-PERSISTED-INVALID',
    'ICM-QUICK-PROMPT-VALID',
    'ICM-QUICK-PROMPT-TOO-FEW-OPTIONS-INVALID',
    'ICM-QUICK-PROMPT-EXPIRED-APPLICATION-VALID',
    'ICM-CORRECTION-CHANGE-AMOUNT-VALID',
    'ICM-CORRECTION-VOID-VALID',
    'ICM-CORRECTION-RESTORE-VALID',
    'ICM-CORRECTION-CROSS-DAY-VALID',
    'ICM-CORRECTION-LEGACY-OPERATION-INVALID',
    'ICM-CORRECTION-MISSING-SNAPSHOT-INVALID',
    'ICM-CORRECTION-DATE-ORDER-INVALID',
    'ICM-CORRECTION-DUPLICATE-DATE-INVALID',
    'ICM-CORRECTION-NO-CHANGE-EVENT-INVALID',
    'ICM-CORRECTION-STALE-WRITE-INVALID',
    'ICM-OUTBOX-PENDING-VALID',
    'ICM-OUTBOX-RETRYABLE-FAILED-VALID',
    'ICM-OUTBOX-PERMANENT-SKIP-VALID',
    'ICM-OUTBOX-TERMINAL-REOPEN-INVALID',
    'ICM-OUTBOX-RETRYABLE-MISSING-REASON-INVALID',
    'ICM-OUTBOX-NEGATIVE-ATTEMPT-INVALID',
    'ICM-FACT-COMMIT-SUCCESS-VALID',
    'ICM-FACT-COMMIT-FAILED-VALID',
    'ICM-FACT-COMMIT-FAILED-BUSINESS-ID-INVALID',
    'ICM-FACT-COMMIT-FAILED-OUTBOX-INVALID',
    'ICM-FACT-COMMIT-SUCCESS-NO-OUTBOX-INVALID',
    'ICM-EFFECT-SUCCEEDED-VALID',
    'ICM-EFFECT-PENDING-VALID',
    'ICM-EFFECT-PERMANENT-SKIP-VALID',
    'ICM-EFFECT-PENDING-RECEIPT-INVALID',
    'ICM-EFFECT-INVENTORY-INSUFFICIENT-VALID',
    'ICM-FINALIZE-COMMITTED-VALID',
    'ICM-FINALIZE-COMMITTED-WITH-ISSUES-VALID',
    'ICM-FINALIZE-EFFECTS-PENDING-VALID',
    'ICM-FINALIZE-PENDING-RECEIPT-INVALID',
    'ICM-FINALIZE-CROSS-DAY-VALID',
    'ICM-FINALIZE-CROSS-DAY-ALIAS-INVALID',
    'ICM-FINALIZE-SINGLE-ALIAS-MISSING-INVALID',
    'ICM-MIXED-ORDERED-VALID',
    'ICM-MIXED-LATER-FAILURE-VALID',
    'ICM-MIXED-SEQUENCE-DUPLICATE-INVALID',
    'ICM-MIXED-SEQUENCE-GAP-INVALID',
    'ICM-MIXED-FAILED-BUSINESS-REF-INVALID',
    'ICM-IDEMPOTENCY-TERMINAL-RETRY-VALID',
    'ICM-IDEMPOTENCY-PENDING-RESUME-VALID',
    'ICM-IDEMPOTENCY-CONFLICT-ZERO-WRITE-VALID',
    'ICM-IDEMPOTENCY-CONFLICT-BUSINESS-WRITE-INVALID'
)

function Fail([string]$Code, [string]$Detail) {
    throw "$Code`:$Detail"
}

if (-not [IO.File]::Exists($SchemaPath)) {
    Fail 'ISSUE_CORRECTION_MIXED_SCHEMA_FILE_MISSING' $SchemaPath
}
if (-not [IO.File]::Exists($FixturePath)) {
    Fail 'ISSUE_CORRECTION_MIXED_FIXTURE_FILE_MISSING' $FixturePath
}

Fail 'ISSUE_CORRECTION_MIXED_SCHEMA_HASH_INVALID' 'candidate schema and fixture hashes are not frozen'
